services:
  api:
    build: ./src
    volumes:
      - ./src:/code
    command: python -m uvicorn main:app --host 0.0.0.0 --port 8001 --reload
    ports:
      - "8001:8001"
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://postgres:vini123@database:5432/mercado_db
      # Variáveis de segurança injetadas diretamente no contêiner:
      - SECRETY_KEY=FSDFSDFSDFSDFSDSDS.ASDASDASDASD
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=10080
    networks:
      - default
      - rede_do_qb_conecta

networks:
  rede_do_qb_conecta:
    external: true
    name: qb_conecta_default