services:
  api:
    build: ./src
    volumes:
      - ./src:/code
    command: python -m uvicorn main:app --host 0.0.0.0 --port 8001 --reload
    ports:
      - "8001:8001"
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://postgres:vini123@database:5432/mercado_db
    networks:
      - default
      - rede_do_qb_conecta

networks:
  rede_do_qb_conecta:
    external: true
    name: qb_conecta_default