services:

  
  database:
    image: postgres:13
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=vini123
      - POSTGRES_DB=mercado_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
    
  api:
    build: ./src
    volumes:
      - ./src:/code
    command: python -m uvicorn main:app --host 0.0.0.0 --port 8001 --reload
    ports:
      - "8001:8001"
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://postgres:vini123@database:5432/mercado_db
      # Variáveis de segurança injetadas diretamente no contêiner:
      - SECRETY_KEY=FSDFSDFSDFSDFSDSDS.ASDASDASDASD
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=10080
    depends_on:
      - database

volumes:
  postgres_data:
