"""Criação inicial das tabelas

Revision ID: 2918b238d0e4
Revises: da5ae75c9f90
Create Date: 2025-10-06 17:46:20.488780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2918b238d0e4'
down_revision: Union[str, Sequence[str], None] = 'da5ae75c9f90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
