upstream fastapi_app {
    # O nome do serviço Docker do seu backend (não precisa mudar)
    server api_gateway:8000;
}

server {
    listen 80;
    server_name 52.67.172.11; 

    # 1. Configuração para o aplicativo Vue (Frontend)
    # Qualquer requisição que comece com /app/ será servida pelo Nginx.
    location /app/ {
        # Diretório onde os arquivos estáticos do Vue foram copiados (no Dockerfile)
        root /usr/share/nginx/html;
        
        # O Nginx procura por arquivos dentro do root + location (Ex: /usr/share/nginx/html/app)
        # É importante que a pasta 'dist' do Vue seja copiada corretamente no Dockerfile.

        # Garante que o Vue Router funcione, redirecionando para index.html se o arquivo não for encontrado.
        try_files $uri $uri/ /app/index.html; 
    }

    # 2. Configuração para o FastAPI (Backend)
    # O tráfego na raiz '/' (e sub-caminhos não definidos acima) é enviado para o FastAPI.
    location / {
        proxy_pass http://fastapi_app;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}